# Generated by Django 5.0 on 2023-12-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customuser_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': '이미 사용중인 이메일입니다.'}, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(error_messages={'unique': '이미 사용중인 별명입니다.'}, max_length=100, unique=True),
        ),
    ]
