# Generated by Django 5.0 on 2023-12-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(blank=True, error_messages={'blank': '별명을 입력해주세요.', 'unique': '이미 사용중인 별명입니다.'}, max_length=100, unique=True),
        ),
    ]
