# Generated by Django 5.0 on 2023-12-12 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_point', models.CharField(max_length=100)),
                ('dest_point', models.CharField(max_length=100)),
                ('depart_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('num', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RentalCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('num', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_point', models.CharField(max_length=100)),
                ('dest_point', models.CharField(max_length=100)),
                ('depart_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('num', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RentalCarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rental_car/%Y/%m/%d/')),
                ('rental_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_car_images', to='traffic.rentalcar')),
            ],
        ),
        migrations.CreateModel(
            name='RentalCarReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('star_score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rental_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_car_reviews', to='traffic.rentalcar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_car_reviews', to='account.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='RentalCarReviewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rental_car_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_car_review_comments', to='traffic.rentalcarreview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_car_review_comments', to='account.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='RentalCarReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rental_car_review/%Y/%m/%d/')),
                ('rental_car_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_car_review_images', to='traffic.rentalcarreview')),
            ],
        ),
    ]
