# Generated by Django 5.0 on 2023-12-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traffic", "0002_bus_price_rentalcar_price_train_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bus",
            name="num",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="rentalcar",
            name="num",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="train",
            name="num",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
