# Generated by Django 5.0 on 2023-12-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0003_alter_bus_num_alter_rentalcar_num_alter_train_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='num',
            field=models.CharField(error_messages={'unique': '이미 존재하는 버스 번호입니다. 다른 버스 번호를 입력해 주세요.'}, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='rentalcar',
            name='num',
            field=models.CharField(error_messages={'unique': '이미 존재하는 차량 번호입니다. 다른 차량 번호를 입력해 주세요.'}, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='train',
            name='num',
            field=models.CharField(error_messages={'unique': '이미 존재하는 기차 번호입니다. 다른 버스 번호를 입력해 주세요.'}, max_length=100, unique=True),
        ),
    ]
