# Generated by Django 5.0 on 2023-12-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0004_alter_bus_num_alter_rentalcar_num_alter_train_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='num',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='rentalcar',
            name='num',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='train',
            name='num',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
