# Generated by Django 5.0 on 2023-12-12 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lodging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('intro', models.TextField()),
                ('notice', models.TextField()),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MainLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lodging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lodging.lodging')),
            ],
        ),
        migrations.CreateModel(
            name='LodgingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=100)),
                ('is_main', models.BooleanField(default=False)),
                ('lodging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lodging.lodging')),
            ],
        ),
        migrations.CreateModel(
            name='LodgingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('star', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lodging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lodging.lodging')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='LodgingReviewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lodging_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lodging.lodgingreview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='LodgingReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=100)),
                ('lodging_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lodging.lodgingreview')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('lodging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lodging.lodging')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=200)),
                ('is_main', models.BooleanField(default=False)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lodging.roomtype')),
            ],
        ),
        migrations.CreateModel(
            name='SubLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('main_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lodging.mainlocation')),
            ],
        ),
        migrations.AddField(
            model_name='lodging',
            name='sub_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lodging.sublocation'),
        ),
    ]
