# Generated by Django 5.0 on 2023-12-12 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('lodging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='lodging',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='lodging.lodging'),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='sub_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lodgings', to='lodging.sublocation'),
        ),
        migrations.AlterField(
            model_name='lodgingimage',
            name='lodging',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lodging_images', to='lodging.lodging'),
        ),
        migrations.AlterField(
            model_name='lodgingreview',
            name='lodging',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lodging_reviews', to='lodging.lodging'),
        ),
        migrations.AlterField(
            model_name='lodgingreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lodging_reviews', to='account.customuser'),
        ),
        migrations.AlterField(
            model_name='lodgingreviewcomment',
            name='lodging_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lodging_review_comments', to='lodging.lodgingreview'),
        ),
        migrations.AlterField(
            model_name='lodgingreviewcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lodging_review_comments', to='account.customuser'),
        ),
        migrations.AlterField(
            model_name='lodgingreviewimage',
            name='lodging_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lodging_review_images', to='lodging.lodgingreview'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_images', to='lodging.roomtype'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='lodging',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='lodging.lodging'),
        ),
        migrations.AlterField(
            model_name='sublocation',
            name='main_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_locations', to='lodging.mainlocation'),
        ),
    ]
