# Generated by Django 5.0 on 2023-12-12 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0002_alter_amenity_lodging_alter_lodging_sub_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lodgingreview',
            old_name='star',
            new_name='star_score',
        ),
    ]
