# Generated by Django 5.0 on 2023-12-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0003_rename_star_lodgingreview_star_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodging',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
