# Generated by Django 5.0 on 2023-12-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0006_alter_lodgingimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgingimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lodging_image/%Y/%m/%d/'),
        ),
    ]
