# Generated by Django 5.0 on 2023-12-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0007_alter_lodgingimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgingimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lodging_images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='lodgingreviewimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lodging_review_images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/%Y/%m/%d/'),
        ),
    ]
