# Generated by Django 5.0 on 2023-12-12 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("account", "0001_initial"),
        ("lodging", "0003_rename_star_lodgingreview_star_score"),
        ("traffic", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bus_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bus_pick",
                        to="traffic.bus",
                    ),
                ),
                (
                    "lodging_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lodging_pick",
                        to="lodging.lodging",
                    ),
                ),
                (
                    "rental_car_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rental_car_pick",
                        to="traffic.rentalcar",
                    ),
                ),
                (
                    "train_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="train_pick",
                        to="traffic.train",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.customuser",
                    ),
                ),
            ],
        ),
    ]
