# Generated by Django 5.0 on 2023-12-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pick', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='pick_type',
            field=models.CharField(choices=[('LG', 'Lodging'), ('TR', 'Train'), ('BU', 'Bus'), ('RC', 'Rental Car')], max_length=100),
        ),
    ]
