# Generated by Django 5.0 on 2023-12-15 14:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0008_alter_lodgingimage_image_and_more'),
        ('pick', '0002_alter_pick_pick_type'),
        ('traffic', '0005_alter_bus_num_alter_rentalcar_num_alter_train_num'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pick',
            constraint=models.UniqueConstraint(fields=('user', 'lodging'), name='unique_lodging_per_user', violation_error_message='이미 찜한 숙소입니다.'),
        ),
        migrations.AddConstraint(
            model_name='pick',
            constraint=models.UniqueConstraint(fields=('user', 'bus'), name='unique_bus_per_user', violation_error_message='이미 찜한 버스입니다.'),
        ),
        migrations.AddConstraint(
            model_name='pick',
            constraint=models.UniqueConstraint(fields=('user', 'train'), name='unique_train_per_user', violation_error_message='이미 찜한 기차입니다.'),
        ),
        migrations.AddConstraint(
            model_name='pick',
            constraint=models.UniqueConstraint(fields=('user', 'rental_car'), name='unique_rental_car_per_user', violation_error_message='이미 찜한 렌트카입니다.'),
        ),
    ]
