# Generated by Django 5.0 on 2023-12-15 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0008_alter_lodgingimage_image_and_more'),
        ('pick', '0003_pick_unique_lodging_per_user_and_more'),
        ('traffic', '0005_alter_bus_num_alter_rentalcar_num_alter_train_num'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pick',
            name='unique_lodging_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='pick',
            name='unique_bus_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='pick',
            name='unique_train_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='pick',
            name='unique_rental_car_per_user',
        ),
        migrations.AddConstraint(
            model_name='pick',
            constraint=models.UniqueConstraint(fields=('user', 'lodging'), name='unique_lodging_per_user'),
        ),
        migrations.AddConstraint(
            model_name='pick',
            constraint=models.UniqueConstraint(fields=('user', 'bus'), name='unique_bus_per_user'),
        ),
        migrations.AddConstraint(
            model_name='pick',
            constraint=models.UniqueConstraint(fields=('user', 'train'), name='unique_train_per_user'),
        ),
        migrations.AddConstraint(
            model_name='pick',
            constraint=models.UniqueConstraint(fields=('user', 'rental_car'), name='unique_rental_car_per_user'),
        ),
    ]
