# Generated by Django 5.0 on 2023-12-12 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_reservation_bus_alter_reservation_end_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='type',
            new_name='reservation_type',
        ),
    ]
