# Generated by Django 5.0 on 2023-12-17 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0008_alter_lodgingimage_image_and_more'),
        ('reservation', '0003_rename_type_reservation_reservation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='lodging',
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='lodging.roomtype'),
        ),
    ]
