name: Django CI/CD

on:
  push:
    branches: [ "deploy" ]
  pull_request:
    branches: [ "deploy" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 체크아웃 레포지토리
      uses: actions/checkout@v3
      
    - name: 파이썬 설정
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        
    - name: 의존성 설치
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Tests
      run: |
        python manage.py test
      env :
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEBUG: ${{ secrets.DEBUG }}

    - name: 서버 배포
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.PEM_SECRET }}
        script: |
          set -e
          cd /home/ubuntu/nolreo_wassup/nolreo_wassup_BE
          git pull origin deploy

          echo "SECRET_KEY=\"${{ secrets.SECRET_KEY }}\"" > .env
          echo "DEBUG='${{ secrets.DEBUG }}'" >> .env

          source ../venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart nolreo_wassup.service
